config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      get :following, :followers
    end
  end

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'login', to: 'sessions#create'
  resources :users
  resources :sessions, only: %i[index new]
  resources :posts
  resources :followings

  root to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :content, presence: true

  def self.default_scope
    order('posts.created_at DESC')
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :Photo, ImageUploader
  mount_uploader :Coverimage, ImageUploader
  has_many :posts, dependent: :destroy
  has_many :followings, foreign_key: 'follower_id', dependent: :destroy
  has_many :followed_users, through: :followings, source: :followed
  has_many :reverse_followings, foreign_key: 'followed_id', class_name: 'Following', dependent: :destroy
  has_many :followers, through: :reverse_followings, source: :follower

  validates_uniqueness_of :Username
  validates :Username, presence: true
  validates :Fullname, presence: true
  validates :Photo, presence: true
  validates :Coverimage, presence: true

  scope :who_to_follow, lambda { |user_id|
                          where(
                            "id NOT IN ( SELECT followed_id
FROM followings
WHERE follower_id = ?
)",
                            user_id
                          )
                        }

  scope :followed_by, lambda { |user_id|
                        where(
                          "id IN ( SELECT follower_id
                 FROM followings
                 WHERE followed_id = ?
               )",
                          user_id
                        )
                      }

  def following?(user)
    followed_users.include?(user)
  end

  def follow!(user2)
    followings.create!(followed_id: user2.id)
  end

  def unfollow!(user2)
    followings.find_by_followed_id(user2.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: 'Not authorized' if current_user.nil?
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def new
    @following = Following.new
  end

  def index
    @followings = Following.all
  end

  def create
    @user = User.find(params[:following][:followed_id])
    current_user.follow!(@user)
    redirect_to @user
  end

  def destroy
    @user = Following.find(params[:id]).followed
    current_user.unfollow!(@user)
    redirect_to @user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize, only: %i[edit update create show]
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    # @post = current_user.posts.build(params[:posts])
    if @post.save
      redirect_to users_path, notice: 'Post created'

    else
      puts @post.errors.full_messages
    end
  end

  def index
    @posts = Post.all.includes(:user)
  end

  def destroy; end

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def index; end

  def create
    @current_user = User.find_by(Username: params[:session][:Username])
    if @current_user
      session[:user_id] = @current_user.id
      redirect_to users_path, notice: 'Logged in'

    else
      flash.now.alert = 'User does not exist'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    @current_user = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to users_path, notice: 'Signed up succesfully'
    else
      puts @user.errors.full_messages
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @post = Post.new
    @posts = @user.posts
  end

  def index
    @post = Post.new
    @posts = Post.all
    @users = User.all
    @users = @users.includes(:posts)
    @who_to_follow = User.who_to_follow(current_user.id)
  end

  def followers
    @head = 'Followers'
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  def user_params
    params.require(:user).permit(:Username, :Fullname, :Photo, :Coverimage)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def aside
    if current_user
      render 'layouts/aside_logged_in'
    else
      render 'layouts/aside_logged_out'
    end
  end

  def navbar_logged_in
    if current_user
      render 'layouts/nav_logged_in'
    else
      render 'layouts/nav_logged_out'
    end
  end
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def who_to_follow?(user)
    render 'users/who_to_follow', { u: user } unless user == current_user
  end

  def following_method(user)
    return if user == current_user

    if current_user.following?(user)
      render 'unfollow'
    else
      render 'follow'
    end
  end
end

app/views/layouts/_aside_logged_in.html.erb
<div class = "mt-3">
<div class = "d-flex flex-row align-items-center justify-content-between">
<a href src="#" class="text-light"><i class="fab fa-twitter "></i> </a>
<h4 class="text-light"> KONNECT </h4>
</div>
<div class="d-flex align-items-center justify-content-between">
<img class = "img-icon" src="<%=current_user.Photo%>"/>
<p class="text-light" ><%=current_user.Username %> </p> 
</div>

<div class = "d-flex justify-content-around">


<div class="d-flex flex-column">
<p class="text-light"> <%= current_user.followed_users.count  %> </p>
<p class="text-light"> Following </p>
</div>
 
<div class="d-flex flex-column">
<p class="text-light"> <%= current_user.followers.count  %> </p>
<p class="text-light"> Followers </p>
</div>

</div>

<p class = "text-light text-center h4" > <%= link_to "Home", users_path %> </p>
<p class = "text-light text-center h4" > <%= link_to "Connect", new_post_path %> </p>
<p class = "text-light text-center h4" > <%= link_to "Profile", @current_user_path %> </p>






</div>

app/views/layouts/_aside_logged_out.html.erb
<div class = "">
<div class = "d-flex flex-row align-items-center justify-content-between">
<a href src="#" class="text-light"><i class="fab fa-twitter "></i> </a>
<h4 class="text-light"> KONNECT </h4>
</div>
</div>

app/views/layouts/_nav_logged_in.html.erb
<div class="d-flex nav-out align-items-center justify-content-between">
<div>
<i class="fab fa-twitter"></i>
</div>
<div class="mx-5">
<p> <%= link_to "Sign out", logout_path, method: "get" %> </p>

</div>
</div>

app/views/layouts/_nav_logged_out.html.erb
<div class="d-flex nav-out align-items-center justify-content-between">
<div>
<i class="fab fa-twitter"></i>
</div>
<div class="mx-5">
<%= link_to "Log in", login_path, method: "get" %>
<%= link_to "Create Account", signup_path %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Konnect</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'style.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script
    src="https://kit.fontawesome.com/16d2250538.js"
    crossorigin="anonymous"
  ></script>
  </head>

  <body>
  <% flash.each do |type, message| %>
    <div><%= message %></div>
<% end %>
<div class = "container-fluid">
<div class = "row">
<div class="col-3 bg-dark aside pt-3">
<%= aside %>
</div>
<div class="col-9">
<nav>

<ul class="navbar d-flex justify-content-between ">
<%=navbar_logged_in%>
</ul>
</nav>
<div>
    <%= yield %>
    </div>
    </div>
    </div>
    </div>
    <br>
    <br>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

  </body>
</html>

app/views/posts/_error_messages.html.erb
<% if object.errors.any? %>
    <p> The form contains <%=pluralize(object.errors.count, "Error") %>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
        <li> <%=msg %> </li>
    <%end%>
        </ul
<%end%>

app/views/posts/_new_post.html.erb
<%= form_for(@post) do |f| %>
    
    <div class="d-flex flex-column">
    <%= f.text_area :content, placeholder: "New post" %>
    <%= f.submit "Create", class: "btn btn-primary"%>
    </div>
<%end%>

app/views/posts/_posts.html.erb
<li>
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
</li>

app/views/posts/index.html.erb
<h3> All Posts, Total: <%=@posts.count%> </h3>
<div class="d-flex flex-column">
<% @posts.each do |post| %>
    <div>
   <img class="h-50 w-25" src='<%=post.user.Photo %>' alt="pic here" />
    <%=post.user.Username %>:
    <%=post.content %>
    </div>
    <%end%>
     
    </div>
    

app/views/posts/new.html.erb
<%= render 'new_post' %>

app/views/users/_follow.html.erb
<%= form_for(current_user.followings.build(followed_id: @user.id)) do |f| %>
    <div><%= f.hidden_field :followed_id %></div>
    <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
  <% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div>
<a href = "<%= following_user_path(@user) %>" >
<strong class="stat">
<%=@user.followed_users.count %>
</strong>
Following
</a>
<a href="<%= followers_user_path(@user) %>">
    <strong class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.followings.find_by_followed_id(@user),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_who_to_follow.html.erb
<div class=" text-dark">
<%= link_to user_path(u), class: "text-dark" do %>
      
<img class="img-icon2 rounded-circle" src="<%=u.Photo%>" /> <%= u.Username %>
<% end %>
</div>

app/views/users/index.html.erb
<div class= "users-nav d-flex justify-content-between align-items-center w-100 ">

<div>
<%= link_to "Posts", posts_path %>
<a class="px-3" href src ="#" > Photos </a>
<a   href src ="#" > Videos </a>
</div>
<h5> who to Follow </h5>

</div>


<div class="d-flex w-100 flex-row">


<div class ="col-8 w-75"> 
<%= render 'posts/new_post' %>
<div>
<h3> All Posts Total: <%=@posts.count%> </h3>
<% @posts.each do |post| %>
  <div>
 <img class=" w-25 mt-3" src='<%=post.user.Photo %>' alt="pic here" />
  <%=post.user.Username %>:
  <%=post.content %>
  </div>
  <%end%>
  
</div>
</div>

<div class ="col-4 d-flex flex-column" >
  <ul class="users-list">

  <% User.who_to_follow(current_user.id).each do |u|%>
  <%= who_to_follow?(u) %>
  <br>
   <% end %>
  </ul>
</div>



</div>

app/views/users/new.html.erb
<div class="mt-5 d-flex justify-content-center align-items-center flex-column">

<%=form_for(@user, :html => {:muiltipart => true}) do |f| %>
<%= render 'posts/error_messages', object: f.object %>
  <div class="mb-4">
    <%=f.label :Username %>
    <%=f.text_field :Username, class: 'form-control', placeholder: 'Enter user name' %>
  </div>

  <div class="mb-4">
    <%=f.label :Fullname %>
    <%=f.text_field :Fullname,  class: 'form-control', placeholder: 'Enter full name' %>
  </div>

  <div class="mb-4"> 
  <fieldset>
  <%= f.label :Photo, 'Photo' %>
  <%= f.hidden_field :Photo_cache %>
  <%= f.file_field :Photo%>
</fieldset>
</div>

<div class="mb-4">
<fieldset>
  <%= f.label :Coverimage, 'Coverimage' %>
  <%= f.hidden_field :Coverimage_cache %>
  <%= f.file_field :Coverimage%>
</fieldset>
</div>

<%= f.submit "Sign Up", class: "btn btn-large btn-primary"%>
<%end%>
</div>

app/views/users/show.html.erb
<div class="d-flex show-view">

<div class="d-flex flex-column w-75">
<img class= "w-100 h-25"src= "<%=@user.Coverimage%>"  alt="pic here" />

<div class= "users-nav d-flex justify-content-between align-items-center w-100 ">

<div>
<%= link_to "Posts", posts_path %>
<a class="px-3" href src ="#" > Photos </a>
<a   href src ="#" > Videos </a>
</div>
</div>

<div class ="col-8 w-100 mb-2"> 
<%= render 'posts/new_post' %>
</div>
 <div>
 <h3> All Posts Total: <%=@posts.count%> </h3>
<% @posts.each do |post| %>
    <div class = "d-flex mb-2">
    <img class = "w-25"src ="<%=@user.Photo%>" alt="pic here" />
    <div class ="d-flex flex-column justify-content-between" >
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
    </div>
    </div>
  </span>

<%end%>
</div>

</div>

<div class="d-flex flex-column"> 
<div class="d-flex justify-content-center align-items-center mt-2">
<img class="w-50 h-50" src = "<%=@user.Photo%>" alt="pic here" />
<p class="px-2"> <%= @user.Username%> </p>
</div>
<div class = "d-flex justify-content-around">
<div class="d-flex flex-column">
<p class=""> <%= @user.followed_users.count  %> </p>
<p class=""> Following </p>
</div>
 
<div class="d-flex flex-column">
<p class=""> <%= @user.followers.count  %> </p>
<p class=""> Followers </p>
</div>

</div>

<div class="d-flex justify-content-center align-items-center">
<%= following_method(@user)%>
</div>
<div class="d-flex flex-column justify-content-center align-items-center">
<h3> Followers </h3>
<% User.followed_by(@user.id).each do |u|%>
 
  
 
   <%= link_to user_path(u), class: "nav-link text-dark" do %>
         
 <img src="<%=u.Photo%>" class="w-25 h-50"/> <%= u.Username %>
 <% end %>
 <br>

          <% end %>
          </div>
</div>

</div>




</div>